-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 20:31:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DeliveryApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DeliveryApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DeliveryApp` DEFAULT CHARACTER SET utf8 ;
USE `DeliveryApp` ;

-- -----------------------------------------------------
-- Table `DeliveryApp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(30) NOT NULL,
  `lastName` VARCHAR(30) NOT NULL,
  `age` VARCHAR(3) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 0,
  `phone` VARCHAR(15) NOT NULL,
  `status` VARCHAR(45) NULL,
  `location` POINT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eMail_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DeliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeliveryApp`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NOT NULL,
  `idDriver` INT NOT NULL,
  `idStaff` INT NOT NULL,
  `dateStart` DATETIME NOT NULL DEFAULT Now(),
  `dateEnd` DATETIME NULL,
  `status` VARCHAR(45) NOT NULL,
  `totalAmount` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user2_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `fk_order_driver_idx` (`idDriver` ASC) VISIBLE,
  INDEX `fk_order_user1_idx` (`idStaff` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `DeliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_driver`
    FOREIGN KEY (`idDriver`)
    REFERENCES `DeliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_staff`
    FOREIGN KEY (`idStaff`)
    REFERENCES `DeliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeliveryApp`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(5,3) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeliveryApp`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Building` VARCHAR(45) NULL,
  `Floor` VARCHAR(45) NULL,
  `location` POINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeliveryApp`.`routeCheckoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`routeCheckoint` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idOrder` INT NOT NULL,
  `time` DATETIME NULL DEFAULT current_timestamp,
  `location` POINT NULL,
  PRIMARY KEY (`id`, `idOrder`),
  INDEX `fk_routePointsTaken_order1_idx` (`idOrder` ASC) VISIBLE,
  CONSTRAINT `fk_routePointsTaken_order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `DeliveryApp`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeliveryApp`.`userSavedAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`userSavedAddress` (
  `user_id` INT NOT NULL,
  `Address_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `Address_id`),
  INDEX `fk_user_has_Address_Address1_idx` (`Address_id` ASC) VISIBLE,
  INDEX `fk_user_has_Address_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_Address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DeliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_Address_Address1`
    FOREIGN KEY (`Address_id`)
    REFERENCES `DeliveryApp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeliveryApp`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`feedback` (
  `idUser` INT NOT NULL,
  `idOrder` INT NOT NULL,
  `description` VARCHAR(300) NOT NULL DEFAULT 'Not reviewed',
  PRIMARY KEY (`idUser`, `idOrder`),
  INDEX `fk_user_has_order_order1_idx` (`idOrder` ASC) VISIBLE,
  INDEX `fk_user_has_order_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_order_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `DeliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_order_order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `DeliveryApp`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeliveryApp`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`warehouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAddress` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_warehouse_address1_idx` (`idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_warehouse_address1`
    FOREIGN KEY (`idAddress`)
    REFERENCES `DeliveryApp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeliveryApp`.`warehouseItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`warehouseItem` (
  `idWarehouse` INT NOT NULL,
  `idItem` INT NOT NULL,
  `itemQuantity` INT(3) NULL,
  PRIMARY KEY (`idWarehouse`, `idItem`),
  INDEX `fk_warehouse_has_item_item1_idx` (`idItem` ASC) VISIBLE,
  INDEX `fk_warehouse_has_item_warehouse1_idx` (`idWarehouse` ASC) VISIBLE,
  CONSTRAINT `fk_warehouse_has_item_warehouse1`
    FOREIGN KEY (`idWarehouse`)
    REFERENCES `DeliveryApp`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warehouse_has_item_item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `DeliveryApp`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeliveryApp`.`orderedWarehouseItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DeliveryApp`.`orderedWarehouseItem` (
  `idOrder` INT NOT NULL,
  `idWarehouse` INT NOT NULL,
  `idItem` INT NOT NULL,
  `orderedQuantity` INT(3) NULL,
  PRIMARY KEY (`idOrder`, `idWarehouse`, `idItem`),
  INDEX `fk_order_has_warehouseItem_warehouseItem1_idx` (`idWarehouse` ASC, `idItem` ASC) VISIBLE,
  INDEX `fk_order_has_warehouseItem_order1_idx` (`idOrder` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_warehouseItem_order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `DeliveryApp`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_warehouseItem_warehouseItem1`
    FOREIGN KEY (`idWarehouse` , `idItem`)
    REFERENCES `DeliveryApp`.`warehouseItem` (`idWarehouse` , `idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
