-- MySQL Script generated by MySQL Workbench
-- Sat Nov 28 22:56:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema deliveryApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deliveryApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deliveryApp` DEFAULT CHARACTER SET utf8 ;
USE `deliveryApp` ;

-- -----------------------------------------------------
-- Table `deliveryApp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(30) NOT NULL,
  `lastName` VARCHAR(30) NOT NULL,
  `age` VARCHAR(3) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `longitude` DECIMAL(10,8) NULL,
  `latitude` DECIMAL(11,8) NULL,
  `role` VARCHAR(45) NULL,
  `driverStatus` VARCHAR(45) NULL,
  `isDeleted` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eMail_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveryApp`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NOT NULL,
  `idDriver` INT NULL,
  `locationDestination` POINT NOT NULL,
  `dateStart` TIMESTAMP NOT NULL,
  `dateEnd` TIMESTAMP NULL,
  `orderStatus` VARCHAR(45) NOT NULL,
  `totalAmount` DECIMAL(9,2) NOT NULL,
  `isDeleted` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user2_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `fk_order_driver_idx` (`idDriver` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `deliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_driver`
    FOREIGN KEY (`idDriver`)
    REFERENCES `deliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveryApp`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `isDeleted` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveryApp`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Building` VARCHAR(45) NULL,
  `Floor` VARCHAR(45) NULL,
  `longitude` DECIMAL(10,8) NOT NULL,
  `latitude` DECIMAL(11,8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveryApp`.`routeCheckpoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`routeCheckpoint` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idOrder` INT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `longitutde` DECIMAL(10,8) NOT NULL,
  `latitude` DECIMAL(11,8) NOT NULL,
  `isDeleted` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_routePointsTaken_order1_idx` (`idOrder` ASC) VISIBLE,
  CONSTRAINT `fk_routePointsTaken_order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `deliveryApp`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveryApp`.`userSavedAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`userSavedAddress` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idAddress` INT NOT NULL,
  INDEX `fk_user_has_Address_Address1_idx` (`idAddress` ASC) VISIBLE,
  INDEX `fk_user_has_Address_user1_idx` (`idUser` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_Address_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `deliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_Address_Address1`
    FOREIGN KEY (`idAddress`)
    REFERENCES `deliveryApp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveryApp`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idOrder` INT NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `isDeleted` TINYINT NOT NULL,
  INDEX `fk_user_has_order_order1_idx` (`idOrder` ASC) VISIBLE,
  INDEX `fk_user_has_order_user1_idx` (`idUser` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_order_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `deliveryApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_order_order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `deliveryApp`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveryApp`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`warehouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAddress` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `isDeleted` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_warehouse_address1_idx` (`idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_warehouse_address1`
    FOREIGN KEY (`idAddress`)
    REFERENCES `deliveryApp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveryApp`.`warehouseItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`warehouseItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idWarehouse` INT NOT NULL,
  `idItem` INT NOT NULL,
  `itemQuantity` INT(3) NOT NULL,
  `isDeleted` TINYINT NOT NULL,
  INDEX `fk_warehouse_has_item_item1_idx` (`idItem` ASC) VISIBLE,
  INDEX `fk_warehouse_has_item_warehouse1_idx` (`idWarehouse` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_warehouse_has_item_warehouse1`
    FOREIGN KEY (`idWarehouse`)
    REFERENCES `deliveryApp`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warehouse_has_item_item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `deliveryApp`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveryApp`.`orderedWarehouseItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryApp`.`orderedWarehouseItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idWarehouseItem` INT NOT NULL,
  `idOrder` INT NOT NULL,
  `orderedQuantity` INT(3) NOT NULL,
  `pricePerUnit` DECIMAL(6,2) NOT NULL,
  INDEX `fk_order_has_warehouseItem_order1_idx` (`idOrder` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_orderedWarehouseItem_warehouseItem1_idx` (`idWarehouseItem` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_warehouseItem_order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `deliveryApp`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderedWarehouseItem_warehouseItem1`
    FOREIGN KEY (`idWarehouseItem`)
    REFERENCES `deliveryApp`.`warehouseItem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `deliveryApp`;

DELIMITER $$
USE `deliveryApp`$$
CREATE DEFINER = CURRENT_USER TRIGGER `deliveryApp`.`user_AFTER_UPDATE` AFTER UPDATE ON `user` FOR EACH ROW
BEGIN
	if New.isDeleted=1 AND Old.isDeleted=0 then 
		DELETE FROM  `userSavedAddress` where userSavedAddress.idUser = New.id;
        UPDATE `order` SET isDeleted=1 where idCustomer=NEW.id;
	end if;
END$$

USE `deliveryApp`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `item_AFTER_UPDATE` AFTER UPDATE ON `item` FOR EACH ROW BEGIN
	IF NEW.isDeleted=1 AND OLD.isDeleted=0 THEN
		UPDATE `warehouseItem` set isDeleted=1 where idItem = NEW.id;
	end if;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
